services:
  anderdata-landing:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        PUBLIC_UMAMI_WEBSITE_ID: ${PUBLIC_UMAMI_WEBSITE_ID}
        PUBLIC_GITHUB_TOKEN: ${PUBLIC_GITHUB_TOKEN}
    container_name: anderdata-landing
    restart: unless-stopped
    networks:
      - apps
    expose:
      - "80"
    ports:
      - "4321:80"
networks:
  apps:
    external: true
