services:
  anderdata-landing:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        VITE_UMAMI_WEBSITE_ID: ${VITE_UMAMI_WEBSITE_ID}
        VITE_GITHUB_TOKEN: ${VITE_GITHUB_TOKEN}
    container_name: anderdata-landing
    restart: unless-stopped
    networks:
      - apps
    expose:
      - "80"

networks:
  apps:
    external: true
